### ISSUE TITLE
Update to use chai 2.x

### ISSUE THREAD

**Issue by pgrm** [chaijs/chai-json-schema#13]
So far chai-version is limited to `< 2` would it be possible to update it to use `2.x` (`2.0.0` has been release last month with a couple of fixes)

**Comment by pgrm** [comment]
Sorry, didn't notice there were already 2 PR - it would be great if https://github.com/Bartvds/chai-json-schema/pull/11 could be pulled. If someone else finds it in the meanwhile, i'm going with the suggestion and using [chai2-json-schema](https://www.npmjs.com/package/chai2-json-schema) for now. 

Hope this gets fixed eventually though.

**Comment by Bartvds** [comment]
Anyone want to take ownership and get this sorted? See https://github.com/Bartvds/chai-json-schema/issues/23

**Comment by JrSchild** [comment]
The dependencies are updated, this will be included in the next release.
