### ISSUE TITLE
chai3 released yet

### ISSUE THREAD

**Issue by darrrk** [chaijs/chai-json-schema#18]
temporary `npm install chai3-json-schema`

**Comment by Petah** [comment]
+1

**Comment by MikeThomas64** [comment]
Even though "npm install chai-json-schema" throws an error with the peer dependencies, it does install and appears to work. Should be a simple matter fix.

**Comment by tauren** [comment]
Can we get this version into bower?

**Comment by Bartvds** [comment]
Anyone want to take ownership and get this sorted? See https://github.com/Bartvds/chai-json-schema/issues/23
