### ISSUE TITLE
Currently published version isn't compatible with the latest chai

### ISSUE THREAD

**Issue by honzajavorek** [chaijs/chai-json-schema#30]
I can't install this package from npm when using Chai v3. Is there any special reason? Is it incompatible? I can see the source code already permits Chai v4, but it's probably not published as a package to npm yet.

**Comment by JrSchild** [comment]
Yes, it is already in master, I'll see if we can do a publish soon. @keithamus Is everything in place for us to push to npm?
For now you could use the latest ref in master in your package.json.

**Comment by keithamus** [comment]
Not yet. I'll get some time tonight to make sure you can publish by making git tags.

**Comment by evansiroky** [comment]
Any updates on publishing to npm?

**Comment by keithamus** [comment]
Sorry I didn't get round to this yet. Thanks for reminding me @evansiroky. I'll try to get some done on this tonight if I can.

**Comment by basharh** [comment]
Any update on this?

**Comment by honzajavorek** [comment]
Bump. [David DM](http://david-dm.org/) punishes me with red badge for having `chai` pinned on an ancient version 😞

**Comment by JrSchild** [comment]
@keithamus?

**Comment by keithamus** [comment]
Yeah sorry, this keeps falling off the bottom of my todo list. I will make sure to do something very soon.

**Comment by honzajavorek** [comment]
If there's still some work needed before release and it's not exclusively maintainer's work, write down what needs to be done and let us contribute it :)

**Comment by keithamus** [comment]
I just need to find the time to sit down and generate a token, sadly not something someone else can do. It's in my todo list, but gets pushed aside for other things including personal life, sadly.

**Comment by janbiasi** [comment]
Any updates at this point?

**Comment by kevinroisin** [comment]
Interested in this as well.

**Comment by keithamus** [comment]
Okay, sorry everyone for taking _forever_ with this. I have opened #33 which fixes it 😅

**Comment by kevinroisin** [comment]
Thanks!

**Comment by honzajavorek** [comment]
This still isn't fixed. Merging #33 didn't publish a new version, because the `package.json` contains the old version number - there's no bump.

**Comment by JrSchild** [comment]
Working on it. Will publish v 1.3.0 soon

**Comment by keithamus** [comment]
It looks as though - in the move to the chaijs org - this repo lost travis integration. I'm working on it to get it published right now.

**Comment by keithamus** [comment]
Aaand 1.3.0 is out! https://www.npmjs.com/package/chai-json-schema
