### ISSUE TITLE
date-time format validation

### ISSUE THREAD

**Issue by setheen** [chaijs/chai-json-schema#31]
Apologies if this is a dupe related to the sub-error issue.  The following succeeds (when it shouldn't) with chai-json-schema yet fails (as expected) with the node `jsonschema` library:

``` javascript
const schema = 
{
    type:"object",
    properties:
    {
        exampleDate:
        {
            type:"string",
            format:"date-time"
        }
    }
};

const mock = 
{
    exampleDate: "erroneous date value"
};

mock.should.be.jsonSchema(schema);
```

**Comment by JrSchild** [comment]
date-time formats seem to work for me though. Try doing it like this:

```
const chai = require('chai');
chai.use(require('chai-json-schema'));

chai.expect({
  exampleDate: '2013-03-25T12:42:31+00:32'
}).to.be.jsonSchema({
  properties: {
    exampleDate: {
      type: 'string',
      format: 'date-time'
    }
  }
});
```

**Comment by JrSchild** [comment]
When using an invalid date-time it still passes. This requires some digging and checking the behavior of the tv4 library.

**Comment by aperdomob** [comment]
Is there some progress in this issue?
