### ISSUE TITLE
peerDependencies error

### ISSUE THREAD

**Issue by solee0524** [chaijs/chai-json-schema#32]
I check your package.json, the peerDependencies shows
```
  "peerDependencies": {
    "chai": ">= 1.6.1 < 4"
  }
```

But when I run `npm install chai-json-schema`, it gives error:

```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "chai-json-schema" "--save"
npm ERR! node v6.0.0
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package chai@3.5.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer chai-json-schema@1.2.0 wants chai@>= 1.6.1 < 3
```

have no idea~

**Comment by JrSchild** [comment]
Master is not pushed to npm yet. Waiting on a PR from @keithamus until we're able to do so. Upgrading to latest master in your package.json will temporarily fix it until we can do a release.
