### ISSUE TITLE
Usage on karma

### ISSUE THREAD

**Issue by canemacchina** [chaijs/chai-json-schema#35]
How to use chai-json-schema with karma?

**Comment by thabemmz** [comment]
We do not have a Karma plugin, nor extensive Karma knowledge to help you.

Feel free to create a plugin for Karma though, it does not seem to be a very complicated implementation (see https://github.com/solatis/karma-chai-things for example).

**Comment by Blatmann** [comment]
I created https://github.com/Blatmann/karma-chai-json-schema based on  https://github.com/solatis/karma-chai-things, as suggested.
