### ISSUE TITLE
Print multiple errors

### ISSUE THREAD

**Issue by Niklv** [chaijs/chai-json-schema#36]
In many cases will be great when assertion prints all found errors in json. For that option library need to use tv4.validateMultiple method.
Is there any workaround to do this?

**Comment by thabemmz** [comment]
This has been resolved in version `1.4.0`, which was just published on NPM. See (README)[https://github.com/chaijs/chai-json-schema/#non-standard-tv4-properties] for instructions how to implement.

**Comment by thabemmz** [comment]
Thanks for your help @Niklv !
