### ISSUE TITLE
type property in schema conflicts with data type 

### ISSUE THREAD

**Issue by kunalkaskar** [chaijs/chai-json-schema#55]
Following Schema always fails to validate, because I have property named type in my schema.

`{
    "type": "array",
    "items": {
        "_id": {
            "type": "string"
        },
        "name" : {
            "type": "string"
        },
        "bankId" : {
            "type": "string"
        },
        "type" : {
            "type": "string"
        },  
    }
  }`

**Comment by edwardsmit** [comment]
This library relies on https://github.com/geraintluff/tv4 for the json validation. Any errors concerning validation should be handled there.
That said, I doubt if your schema is valid per the definitions. At https://www.jsonschemavalidator.net your schema also does not validate.
