### ISSUE TITLE
Newer drafts of JSON Schema

### ISSUE THREAD

**Issue by philsturgeon** [chaijs/chai-json-schema#63]
Hey there! JSON Schema draft 4 is pretty old now. The project is currently on draft 7, most tools around support at least draft 6. 

Instead of using [tv4 which is also only support draft 4](https://github.com/geraintluff/tv4/issues/261), you could use [another validator](https://json-schema.org/implementations.html#validator-javascript) which is keeping up to date. For example, AJV has support for draft 4, 5, 6 and 7, so that should help, and it'll make updates easier in the future - especially as you have greenkeeper. It'll just let you know when a new version is out, with new drafts. 🙌

I don't use Chai enough to be able to justify working on this sadly, otherwise I'd be happy to turn this into a PR. If you have any questions I'm all ears. :)

**Comment by edwardsmit** [comment]
Hi @philsturgeon, I understand your lack of justification, and a lot of developers have the same problem. But such is the nature of Open Source, you're free to use it, and free to enhance it, but nobody is obliged to update the software.
Anyone really needing such an update is free to create a PR.

**Comment by edwardsmit** [comment]
@philsturgeon Maybe https://github.com/up9cloud/chai-json-schema-ajv is a good alternative for you?

**Comment by philsturgeon** [comment]
I didn't say anything about obligation I wasn't chastising you! The point was that if you are interested there is newer libraries that can be used to help your tool support newer drafts. Do what you will with that information. :)

**Comment by edwardsmit** [comment]
@philsturgeon And I wasn't feeling chastised nor was I implying that you were. It was just a general thought of mine. I apologize if you felt attacked or offended in any way, that was not what I was trying to get across.

**Comment by philsturgeon** [comment]
Cool! I didn't I was just worried it came across wrong. 

![giphy](https://user-images.githubusercontent.com/67381/56372728-d59e8000-61ff-11e9-8ab7-a412cc00c04e.gif)
